name: Integration
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

permissions:
      id-token: write
      contents: write

jobs:
  Integration:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2.0.2

      - name: Test
        run: |
          cd test
          go mod init "terraform-mod-network"
          go mod tidy
          go test -v -timeout 30m